# .github/release.yml
changelog:
  exclude:
    authors:
      - "*"
  categories:
    - title: Major Upgrades 🛠
      labels:
        - major-upgrade
    - title: Exciting New Features 🎉
      labels:
        - enhancement
    - title: Bug Fixes
      labels:
          - bug
    - title: Other Changes
      labels:
        - "*"
