disabled_rules:
  - leading_whitespace
  - trailing_whitespace
  - identifier_name
  - line_length
  - private_over_fileprivate

opt_in_rules:
  - empty_count
  - accessibility_label_for_image
  - accessibility_trait_for_button
  - notification_center_detachment
  - yoda_condition

analyzer_rules:
  - unused_declaration
  - unused_import
  - explicit_self

excluded:
  - Derived
  - Tuist/.build
  - "**/.build"

custom_rules:
  sf_safe_symbol:
    name: "Safe SFSymbol"
    message: "Use `SFSafeSymbols` via `systemSymbol` parameters for type safety."
    regex: "(Image\\(systemName:)|(NSImage\\(symbolName:)|(Label[^,]+?,\\s*systemImage:)|(UIApplicationShortcutIcon\\(systemImageName:)"
    severity: warning
