//
//  GeneratingWordlist.swift
//  Minna
//
//  Created by Taylor Lineman on 7/8/26.
//

extension Wordlists {
    static let generatingContentQuips: [String] = [
        "Thinking",
        "Pondering",
        "Reasoning",
        "Analyzing",
        "Synthesizing",
        "Computing",
        "Calculating",
        "Processing",
        "Parsing",
        "Searching",
        "Scanning",
        "Retrieving",
        "Fetching",
        "Consulting",
        "Researching",
        "Investigating",
        "Exploring",
        "Examining",
        "Reviewing",
        "Evaluating",
        "Assessing",
        "Considering",
        "Contemplating",
        "Reflecting",
        "Musing",
        "Deliberating",
        "Formulating",
        "Drafting",
        "Composing",
        "Crafting",
        "Constructing",
        "Assembling",
        "Building",
        "Generating",
        "Creating",
        "Designing",
        "Planning",
        "Mapping",
        "Charting",
        "Tracing",
        "Digesting",
        "Absorbing",
        "Interpreting",
        "Understanding",
        "Comprehending",
        "Untangling",
        "Unpacking",
        "Distilling",
        "Refining",
        "Polishing",
        "Finalizing",
        "Wrapping up",
        "Cross-referencing",
        "Fact-checking",
        "Double-checking",
        "Verifying",
        "Confirming",
        "Simulating",
        "Modeling",
        "Consulting the oracle",
        "Summoning the muses",
        "Channeling brainpower",
        "Warming up the neurons",
        "Spinning up thoughts",
        "Crunching numbers",
        "Connecting the dots",
        "Piecing together",
        "Weighing options",
        "Sorting through data",
        "Sifting through information",
        "Filtering results",
        "Cross-checking facts",
        "Brewing ideas",
        "Cooking up a response",
        "Percolating",
        "Incubating ideas",
        "Loading", 
        "Booting up",
        "Waking up",
        "Gathering thoughts"
    ]
}
